### ISSUE TITLE
chase deprecated ohai cookbook dependency

### ISSUE THREAD

**Issue by jgh9** [KierranM/ec2-tags-ohai-plugin#13]
Ohai cookbook has been deprecated, and I took a stab at removing it from cookbook, however tests are failing. I created a fork and branch for adjusting cookbook.

https://github.com/jgh9/ec2-tags-ohai-plugin/tree/adjust-dependencies-cleanup

```
EC2 Tags plugin
         File "/opt/node.json"
           is expected to exist
         created-by
           should be test-kitchen (FAILED - 1)
         example-tag
           should be example (FAILED - 2)

      
      Failures:
      
         1) EC2 Tags plugin created-by should be test-kitchen
            Failure/Error: expect(node_data['automatic']['ec2']['tags']['created-by']).to eq 'test-kitchen'
            NoMethodError:
              undefined method `[]' for nil:NilClass
             
            # /tmp/verifier/suites/serverspec/default_spec.rb:14:in `block (3 levels) in <top (required)>'
      
         2) EC2 Tags plugin example-tag should be example
            Failure/Error: expect(node_data['automatic']['ec2']['tags']['example-tag']).to eq 'example'
            NoMethodError:
              undefined method `[]' for nil:NilClass
             
            # /tmp/verifier/suites/serverspec/default_spec.rb:20:in `block (3 levels) in <top (required)>'
      
       Finished in 0.04595 seconds (files took 0.4354 seconds to load)
       3 examples, 2 failures
      
       Failed examples:
      
       rspec /tmp/verifier/suites/serverspec/default_spec.rb:13 # EC2 Tags plugin created-by should be test-kitchen
       rspec /tmp/verifier/suites/serverspec/default_spec.rb:19 # EC2 Tags plugin example-tag should be example
```

**Comment by jgh9** [comment]
https://github.com/chef/chef/issues/12363

**Comment by jgh9** [comment]
I will open a pull request to address this issue.
