### ISSUE TITLE
EC2Tags dont work on latest windows images

### ISSUE THREAD

**Issue by Mor-Walkme** [KierranM/ec2-tags-ohai-plugin#9]
Hey,
I am trying to get it work on windows images both 2012 and 2016, while getting the following error:
[2018-08-05T11:18:53+00:00] DEBUG: Plugin EC2Tags threw #<NameError: uninitialized constant Aws>
[2018-08-05T11:18:53+00:00] DEBUG: C:/chef/ohai/plugins/ec2-tags.rb:25:in `rescue in block (2 levels) in <main>'
[2018-08-05T11:18:53+00:00] DEBUG: C:/chef/ohai/plugins/ec2-tags.rb:9:in `block (2 levels) in <main>'
[2018-08-05T11:18:53+00:00] DEBUG: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/ohai-13.8.0/lib/ohai/dsl/plugin/versionvii.rb:90:in `instance_eval'
[2018-08-05T11:18:53+00:00] DEBUG: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/ohai-13.8.0/lib/ohai/dsl/plugin/versionvii.rb:90:in `run_plugin'
[2018-08-05T11:18:53+00:00] DEBUG: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/ohai-13.8.0/lib/ohai/dsl/plugin.rb:102:in `run'
[2018-08-05T11:18:53+00:00] DEBUG: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/ohai-13.8.0/lib/ohai/dsl/plugin.rb:185:in `safe_run'
[2018-08-05T11:18:53+00:00] DEBUG: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/ohai-13.8.0/lib/ohai/runner.rb:90:in `run_v7_plugin'
[2018-08-05T11:18:53+00:00] DEBUG: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/ohai-13.8.0/lib/ohai/runner.rb:47:in `block in run_plugin'
[2018-08-05T11:18:53+00:00] DEBUG: C:/opscode/chef/embedded/lib/ruby/2.4.0/benchmark.rb:293:in `measure'
[2018-08-05T11:18:53+00:00] DEBUG: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/ohai-13.8.0/lib/ohai/runner.rb:39:in `run_plugin'
[2018-08-05T11:18:53+00:00] DEBUG: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/ohai-13.8.0/lib/ohai/system.rb:105:in `block in run_plugins'
[2018-08-05T11:18:53+00:00] DEBUG: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/ohai-13.8.0/lib/ohai/system.rb:104:in `each'
[2018-08-05T11:18:53+00:00] DEBUG: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/ohai-13.8.0/lib/ohai/system.rb:104:in `run_plugins'
[2018-08-05T11:18:53+00:00] DEBUG: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/ohai-13.8.0/lib/ohai/system.rb:82:in `all_plugins'
[2018-08-05T11:18:53+00:00] DEBUG: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/ohai-13.8.0/lib/ohai/application.rb:97:in `run_application'
[2018-08-05T11:18:53+00:00] DEBUG: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/ohai-13.8.0/lib/ohai/application.rb:80:in `block in run'
[2018-08-05T11:18:53+00:00] DEBUG: C:/opscode/chef/embedded/lib/ruby/2.4.0/benchmark.rb:293:in `measure'
[2018-08-05T11:18:53+00:00] DEBUG: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/ohai-13.8.0/lib/ohai/application.rb:78:in `run'
[2018-08-05T11:18:53+00:00] DEBUG: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/ohai-13.8.0/bin/ohai:26:in `<top (required)>'
[2018-08-05T11:18:53+00:00] DEBUG: C:/opscode/chef/bin/ohai:29:in `load'
[2018-08-05T11:18:53+00:00] DEBUG: C:/opscode/chef/bin/ohai:29:in `<main>'

Some details:
Base AMI: ami-f7ece81c , also tried: ami-8017156b
Gem version: C:\opscode\chef\embedded\bin\gem list
aws-sdk (2.0.48)
aws-sdk-core (2.0.48)
aws-sdk-resources (2.0.48)

Please assist.
Thanks,
Mor.

**Comment by KierranM** [comment]
Hey @Mor-Walkme, can you try pinning to `0.2.3` please? The latest version was meant to support aws-sdk V3

**Comment by Mor-Walkme** [comment]
Works on 0.2.3, thanks alot
